---
# This playbook used to break a perfectly good OpenStack cloud 

- hosts: allinoneA
  remote_user: root
  become: true
  roles:
    - create-instance
    
- hosts: allinoneB
  remote_user: root
  become: true
  roles:
    - create-instance
