---

- name: Stop openstack service
  command: ansible "{{ containernam1 }}" -m shell -a "service {{ servicenam }} stop" -i "/opt/openstack-ansible/playbooks/inventory/dynamic_inventory.py"
  ignore_errors: yes
  
- name: Adjust tenant quotas
  command: ansible "{{ containernam2 }}" -m shell -a "openstack --os-cloud={{ CLOUD_NAME }} quota set {{ item.1 }} {{ item.0 }}" 
           -i "/opt/openstack-ansible/playbooks/inventory/dynamic_inventory.py"
  with_together:
    - "{{qoptions}}"
    - "{{tenantname}}"